' ======================================================================
' Vivaldi bottom-layer feed + radial stub
' Generated by Antenna Designer
' ======================================================================
'
' The macro is self-contained — it AUTO-CREATES any missing
' parameters (with the values you exported from the GUI).
' If a parameter already exists in your CST project, your
' value wins. So you can paste-and-run on a blank project,
' OR onto a project where you've already tweaked some of
' the knobs by hand.
'
' Project units MUST match what you exported in (the
' default values below assume the same unit system).
'
' How to run:
'   Macros > Edit/Run VBA Macro... > paste this whole file,
'   click Run.   OR  save as .bas and use Macros > Run Macro.
'
' Tunable knobs (sweep any of these in CST's Parameter List
' after the macro runs and the bottom layer rebuilds):
'   x_cross       - slot-crossing position (balun centre freq)
'   stub_r        - radial-stub radius (virtual-short freq)
'   stub_ang      - sector full angle, deg (balun bandwidth)
'   feed_w_slot   - microstrip width at slot (Z-match)
'   W_feed        - main microstrip width (Z0)
'   miter_d       - corner chamfer (bend compensation)
'

Sub Main ()

' ============================================================
' VERTICAL PLACEMENT — set at runtime via dialog
' ============================================================
'
' A dialog pops up so you can type the expression that gives
' the z-coordinate where the TOP face of the bottom copper sits.
' The copper extrudes DOWNWARD by t_cu from there.
'
' To skip the prompt on future runs, just hard-code the line
' Z_FEED_TOP = "..." with whatever you ended up using.
'
Dim Z_FEED_TOP As String
Dim defaultZ As String
Dim probeMaskH As Double
On Error Resume Next
probeMaskH = RestoreDoubleParameter("mask_h")
If Err.Number = 0 Then
    defaultZ = "mask_h + t_cu"
Else
    Err.Clear
    defaultZ = "-h"
End If
On Error Goto 0

' Resolve t_cu to a numeric value for ExtrudeCurve.Thickness
' (CST's ExtrudeCurve expects a Double for Thickness, not a
' string expression — passing strings caused the extrude to
' go the wrong direction in earlier macro versions.)
Dim tCuVal As Double
tCuVal = RestoreDoubleParameter("t_cu")

Z_FEED_TOP = InputBox( _
    "Where should the TOP face of the bottom copper sit?" & vbCrLf & _
    "(The copper then extrudes DOWNWARD by t_cu from there,)" & vbCrLf & _
    "(so its bottom ends up at Z_FEED_TOP - t_cu.)" & vbCrLf & vbCrLf & _
    "Examples (type any CST expression):" & vbCrLf & _
    "   0                 substrate sits at [0, h]" & vbCrLf & _
    "   -h                substrate sits at [-h, 0]" & vbCrLf & _
    "   mask_h            substrate sits at [mask_h, ...]" & vbCrLf & _
    "   mask_h + t_cu     substrate sits at [mask_h+t_cu, ...]" & vbCrLf & vbCrLf & _
    "Tip: its the SAME value as the z-coordinate of the bottom face" & vbCrLf & _
    "of your substrate solid. Easy way to check: pick that face in CST.", _
    "Vivaldi - Bottom Copper Placement", _
    defaultZ)

If Z_FEED_TOP = "" Then
    MsgBox "Cancelled. No copper was built."
    Exit Sub
End If

' ExtrudeCurve in this CST version places the extruded solid
' with its BOTTOM at the curve plane (not the top), regardless
' of Thickness sign. So to land the copper TOP at Z_FEED_TOP,
' we translate by (Z_FEED_TOP - t_cu).
Dim translateZ As String
translateZ = "(" & Z_FEED_TOP & ") - t_cu"

' --- Ensure feed/stub geometry parameters exist (idempotent
'     — won't clobber any value you've already entered) ---
EnsureParam "h", 1.51   ' Substrate thickness
EnsureParam "t_cu", 0.035   ' Copper layer thickness (1 oz default)
EnsureParam "W_feed", 3.04462   ' Microstrip width, horizontal run
EnsureParam "feed_w_slot", 0.5   ' Microstrip width at the slot crossing
EnsureParam "miter_d", 1.82677   ' Outer L-bend chamfer depth
EnsureParam "stub_r", 8.45816   ' Radial-stub radius
EnsureParam "stub_ang", 90   ' Radial-stub full sector angle (deg)
EnsureParam "x_cross", -2.97459   ' Slot-crossing x (board-centered)
EnsureParam "y_run", -21.1607   ' Horizontal-run y (board-centered)
EnsureParam "x_sma", -47.6385   ' SMA pad x (board-centered)

WCS.ActivateWCS "global"

' ============================================================
' 1. Combined feed + stub closed polygon (single curve)
' ============================================================

With Line
     .Reset
     .Name "fs_s1"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_sma"
     .Y1 "y_run + W_feed/2"
     .X2 "x_cross - W_feed/2"
     .Y2 "y_run + W_feed/2"
     .Create
End With

With Line
     .Reset
     .Name "fs_s2"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross - W_feed/2"
     .Y1 "y_run + W_feed/2"
     .X2 "x_cross - feed_w_slot/2"
     .Y2 "0"
     .Create
End With

With Line
     .Reset
     .Name "fs_s3"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross - feed_w_slot/2"
     .Y1 "0"
     .X2 "x_cross + stub_r*cos((90 + stub_ang/2)*pi/180)"
     .Y2 "stub_r*sin((90 + stub_ang/2)*pi/180)"
     .Create
End With

With Arc
     .Reset
     .Name "fs_s4"
     .Curve "vivaldi_bottom_outline"
     .Orientation "Clockwise"
     .XCenter "x_cross"
     .YCenter "0"
     .X1 "x_cross + stub_r*cos((90 + stub_ang/2)*pi/180)"
     .Y1 "stub_r*sin((90 + stub_ang/2)*pi/180)"
     .Angle "stub_ang"
     .UseAngle "True"
     .Segments "0"
     .Create
End With

With Line
     .Reset
     .Name "fs_s5"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross + stub_r*cos((90 - stub_ang/2)*pi/180)"
     .Y1 "stub_r*sin((90 - stub_ang/2)*pi/180)"
     .X2 "x_cross + feed_w_slot/2"
     .Y2 "0"
     .Create
End With

With Line
     .Reset
     .Name "fs_s6"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross + feed_w_slot/2"
     .Y1 "0"
     .X2 "x_cross + W_feed/2"
     .Y2 "y_run + W_feed/2"
     .Create
End With

With Line
     .Reset
     .Name "fs_s7"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross + W_feed/2"
     .Y1 "y_run + W_feed/2"
     .X2 "x_cross + W_feed/2"
     .Y2 "y_run - W_feed/2 + miter_d"
     .Create
End With

With Line
     .Reset
     .Name "fs_s8"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross + W_feed/2"
     .Y1 "y_run - W_feed/2 + miter_d"
     .X2 "x_cross + W_feed/2 - miter_d"
     .Y2 "y_run - W_feed/2"
     .Create
End With

With Line
     .Reset
     .Name "fs_s9"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_cross + W_feed/2 - miter_d"
     .Y1 "y_run - W_feed/2"
     .X2 "x_sma"
     .Y2 "y_run - W_feed/2"
     .Create
End With

With Line
     .Reset
     .Name "fs_s10"
     .Curve "vivaldi_bottom_outline"
     .X1 "x_sma"
     .Y1 "y_run - W_feed/2"
     .X2 "x_sma"
     .Y2 "y_run + W_feed/2"
     .Create
End With

' Extrude the closed loop into a thin copper solid
' Keep DeleteProfile False so the source curve survives —
' some CST tools (port extension calc, in particular) need
' the original curve in the navigation tree for downstream ops.
With ExtrudeCurve
     .Reset
     .Name "vivaldi_feed"
     .Component "component1"
     .Material "PEC"
     .Thickness -tCuVal
     .Twistangle "0.0"
     .Taperangle "0.0"
     .DeleteProfile "False"
     .Curve "vivaldi_bottom_outline:fs_s1"
     .Create
End With

' Translate so the copper TOP face sits at Z_FEED_TOP
With Transform
     .Reset
     .Name "component1:vivaldi_feed"
     .Vector "0", "0", translateZ
     .UsePickedPoints "False"
     .InvertPickedPoints "False"
     .MultipleObjects "False"
     .GroupObjects "False"
     .Repetitions "1"
     .MultipleSelection "False"
     .Transform "Shape", "Translate"
End With

End Sub

' --- helper: create parameter only if it doesn't exist yet ---
Sub EnsureParam(pname As String, pdefault As Double)
    On Error Resume Next
    Dim v As Double
    v = RestoreDoubleParameter(pname)
    If Err.Number <> 0 Then
        Err.Clear
        StoreDoubleParameter pname, pdefault
    End If
    On Error Goto 0
End Sub
