' Full tunable CST model: Rectangular Patch - Rear-Fed
' Generated by Antenna Designer
' Edit the Parameter List in CST, then Rebuild to retune dimensions.

Sub Main ()
    With Units
        .Geometry "mm"
        .Frequency "GHz"
        .Time "ns"
        .TemperatureUnit "Kelvin"
    End With

    ' Parameter List values
    StoreDoubleParameter "fr_GHz", 5.35
    StoreDoubleParameter "er", 4.1
    StoreDoubleParameter "tan_d", 0.0013
    StoreDoubleParameter "W", 17.545543877
    StoreDoubleParameter "L", 13.3040259085
    StoreDoubleParameter "dielectric_t", 1.51
    StoreDoubleParameter "top_cu_t", 0.035
    StoreDoubleParameter "bot_cu_t", 0.035
    StoreDoubleParameter "Ls", 15
    StoreDoubleParameter "Ws", 15
    StoreDoubleParameter "x_feed", 1.76281185587
    StoreDoubleParameter "pin_rad", 0.635
    StoreDoubleParameter "sma_rad", 2.12438946129
    StoreDoubleParameter "pin_ext", 0

    Solver.FrequencyRange "fr_GHz*0.75", "fr_GHz*1.25"

With Material
     .Reset
     .Name "Antenna_Substrate"
     .Type "Normal"
     .Epsilon "er"
     .Mue "1.0"
     .TanD "tan_d"
     .Create
End With

With Brick
     .Reset
     .Name "Substrate"
     .Component "Antenna"
     .Material "Antenna_Substrate"
     .Xrange "-L/2 - Ls", "L/2 + Ls"
     .Yrange "-W/2 - Ws", "W/2 + Ws"
     .Zrange "bot_cu_t", "bot_cu_t + dielectric_t"
     .Create
End With

With Brick
     .Reset
     .Name "Ground"
     .Component "Antenna"
     .Material "PEC"
     .Xrange "-L/2 - Ls", "L/2 + Ls"
     .Yrange "-W/2 - Ws", "W/2 + Ws"
     .Zrange "0", "bot_cu_t"
     .Create
End With

With Brick
     .Reset
     .Name "Patch"
     .Component "Antenna"
     .Material "PEC"
     .Xrange "-L/2", "L/2"
     .Yrange "-W/2", "W/2"
     .Zrange "bot_cu_t + dielectric_t", "bot_cu_t + dielectric_t + top_cu_t"
     .Create
End With

With Cylinder
     .Reset
     .Name "Feed_Pin"
     .Component "Antenna"
     .Material "PEC"
     .OuterRadius "pin_rad"
     .InnerRadius "0"
     .Axis "z"
     .Zrange "0", "bot_cu_t + dielectric_t + top_cu_t + pin_ext"
     .Xcenter "x_feed"
     .Ycenter "0"
     .Segments "0"
     .Create
End With

With Cylinder
     .Reset
     .Name "Coax_Dielectric_Plug"
     .Component "Antenna"
     .Material "Antenna_Substrate"
     .OuterRadius "sma_rad"
     .InnerRadius "pin_rad"
     .Axis "z"
     .Zrange "0", "bot_cu_t"
     .Xcenter "x_feed"
     .Ycenter "0"
     .Segments "0"
     .Create
End With

    Solid.Insert "Antenna:Ground", "Antenna:Coax_Dielectric_Plug"

    On Error Resume Next
    Port.Delete "1"
    On Error Goto 0
    With Port
         .Reset
         .PortNumber "1"
         .Label "coax_feed"
         .NumberOfModes "1"
         .AdjustPolarization "False"
         .PolarizationAngle "0.0"
         .ReferencePlaneDistance "0"
         .Coordinates "Free"
         .Orientation "positive"
         .Xrange "x_feed - sma_rad", "x_feed + sma_rad"
         .Yrange "-sma_rad", "sma_rad"
         .Zrange "0", "0"
         .XrangeAdd "0", "0"
         .YrangeAdd "0", "0"
         .ZrangeAdd "0", "0"
         .SingleEnded "False"
         .WaveguideMonitor "False"
         .Create
    End With

    Rebuild
End Sub
