(function(){function m(k,l,f){function a(d,e){if(!l[d]){if(!k[d]){var g="function"==typeof require&&require;if(!e&&g)return g(d,!0);if(b)return b(d,!0);e=Error("Cannot find module '"+d+"'");throw e.code="MODULE_NOT_FOUND",e;}e=l[d]={exports:{}};k[d][0].call(e.exports,function(h){return a(k[d][1][h]||h)},e,e.exports,m,k,l,f)}return l[d].exports}for(var b="function"==typeof require&&require,c=0;c<f.length;c++)a(f[c]);return a}return m})()({1:[function(m,k,l){var f={preloadInit:function(){var a=document.getElementById("template_offcanvas");
f.isMobileWidth()||!f.isTocOpen()||a.classList.contains("offcanvas_fixed")||(document.getElementById("template_offcanvas").classList.add("no_animate"),document.getElementById("offcanvas_menu").classList.add("show"),document.getElementById("offcanvas_actuator").classList.add("collapsed"),document.getElementById("offcanvas_actuator").setAttribute("aria-expanded","true"),document.getElementById("offcanvas_menu_content").removeAttribute("aria-hidden"))},init:function(){var a=this;a.updateWidthsAndHeights();
a.relocateNav();a.toggleNavListWrapper();document.addEventListener("scroll",function(){a.updateWidthsAndHeights()});["resize","orientationchange"].forEach(function(b){window.addEventListener(b,function(){a.updateWidthsAndHeights();a.relocateNav()})});window.addEventListener("updateOffcanvasWidthsAndHeights",function(){a.updateWidthsAndHeights()});document.getElementById("offcanvas_actuator").addEventListener("click",function(b){b=b.currentTarget.getAttribute("aria-expanded");var c=document.getElementById("template_offcanvas"),
d=document.getElementById("offcanvas_menu_content");a.setTOCSession("true"===b);c.classList.remove("no_animate");"true"===b?(d.removeAttribute("aria-hidden"),d.querySelectorAll("a").forEach(function(e){e.removeAttribute("aria-hidden");e.removeAttribute("tabindex")})):(d.setAttribute("aria-hidden","true"),d.querySelectorAll("a").forEach(function(e){e.setAttribute("aria-hidden","true");e.setAttribute("tabindex","-1")}))});document.getElementById("offcanvas_focus_actuator").addEventListener("focus",
function(){var b=document.getElementById("offcanvas_actuator").getAttribute("aria-expanded"),c=document.getElementById("offcanvas_menu"),d=document.getElementById("offcanvas_menu_content");"true"===b&&(new bootstrap.Collapse(c,{toggle:!0}),d.setAttribute("aria-hidden","true"),d.querySelectorAll("a").forEach(function(e){e.setAttribute("aria-hidden","true");e.setAttribute("tabindex","-1")}))})},toggleNavListWrapper:function(){var a=document.getElementById("offcanvas_actuator").getAttribute("aria-expanded"),
b=document.getElementById("offcanvas_menu_content");"true"===a||"offcanvas_fixed_menu_container"===b.parentElement.id?setTimeout(function(){b.removeAttribute("aria-hidden");b.querySelectorAll("a").forEach(function(c){c.removeAttribute("aria-hidden");c.removeAttribute("tabindex")})},700):setTimeout(function(){b.setAttribute("aria-hidden","true");b.querySelectorAll("a").forEach(function(c){c.setAttribute("aria-hidden","true");c.setAttribute("tabindex","-1")})},700)},updateWidthsAndHeights:function(){var a,
b=null==(a=document.getElementsByTagName("header"))?void 0:a[0],c=document.getElementById("sticky_container");a=document.getElementById("offcanvas_body");var d=window.innerWidth,e=d;b&&(e-=getComputedStyle(b).getPropertyValue("width").slice(0,-2));var g=window.innerHeight;b=b?b.offsetHeight:0;var h=c?c.offsetHeight:0;c=g-b-h;var p=document.body.classList.contains("-has_usernav");p&&(c=g-h);h=g-h;var n=Math.max(window.scrollY,document.documentElement.scrollTop,document.body.scrollTop),r=c+n,q=document.querySelector("footer").getBoundingClientRect();
g=Math.max(0,Math.min(q.bottom,g)-Math.max(q.top,0));0===n?f.setOffCanvasState({locked:!1,menuHeight:c,visibleFooterHeight:g}):n>b||p?f.setOffCanvasState({locked:!0,menuHeight:h,visibleFooterHeight:g}):f.setOffCanvasState({locked:!1,menuHeight:r,visibleFooterHeight:g});a.style.width=768>d?"calc(100vw - "+(e+37)+"px)":"auto"},setOffCanvasState:function(a){var b=a.locked,c=a.menuHeight;a=a.visibleFooterHeight;var d=document.getElementById("offcanvas_menu"),e=document.getElementById("template_offcanvas"),
g=document.getElementById("offcanvas_fixed_menu_container"),h=document.getElementById("offcanvas_body").classList.contains("-has_stickynav");e.classList.toggle("locked",b);d.style.height=c+"px";h&&(g.style.maxHeight=c-a+"px")},relocateNav:function(){var a=document.getElementById("template_offcanvas"),b=document.getElementById("offcanvas_menu_content");a.classList.contains("offcanvas_fixed")&&(992>window.innerWidth&&"offcanvas_fixed_menu_container"===b.parentElement.id?(document.getElementById("offcanvas_actuator").insertAdjacentElement("afterend",
b),f.toggleNavListWrapper()):992<=window.innerWidth&&"offcanvas_fixed_menu_container"!==b.parentElement.id&&(document.getElementById("offcanvas_fixed_menu_container").insertAdjacentElement("beforeend",b),f.toggleNavListWrapper()))},isTocOpen:function(){var a=sessionStorage.getItem(this.getSessionName());return null===a||"true"===a},setTOCSession:function(a){sessionStorage.setItem(this.getSessionName(),a)},getSessionName:function(){var a=document.getElementById("offcanvas_menu").dataset.offcanvasId;
return"MW_toc_visible::"+(a?a:location.pathname)},isMobileWidth:function(){return 768>document.body.clientWidth}};k.exports=f;f.preloadInit();document.addEventListener("DOMContentLoaded",function(){f.init()})},{}]},{},[1]);