var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(v){return v.raw=v};$jscomp.createTemplateTagFirstArgWithRaw=function(v,x){v.raw=x;return v};
(function(){function v(x,B,n){function m(g,r){if(!B[g]){if(!x[g]){var E="function"==typeof require&&require;if(!r&&E)return E(g,!0);if(a)return a(g,!0);r=Error("Cannot find module '"+g+"'");throw r.code="MODULE_NOT_FOUND",r;}r=B[g]={exports:{}};x[g][0].call(r.exports,function(y){return m(x[g][1][y]||y)},r,r.exports,v,x,B,n)}return B[g].exports}for(var a="function"==typeof require&&require,e=0;e<n.length;e++)m(n[e]);return m}return v})()({1:[function(v,x,B){var n=v("web-vitals");window.webVitalsData=
{};window.webVitalsDataConfig={};var m={init:function(){if(!/bot|crawl|spider/i.test(navigator.userAgent)){var a=this;a.sendCount=0;a.maxSend=3;n.onCLS(a.addCLSToQueue);n.onLCP(a.addLCPToQueue);n.onFCP(a.addFCPToQueue);n.onTTFB(a.addTTFBToQueue);n.onINP(a.addINPToQueue);a.getConfigs();addEventListener("error",function(e){a.handleJSError(a,e)});addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&m.sendPerformanceData()});addEventListener("pagehide",function(){m.sendPerformanceData()})}},
getConfigs:function(){var a=this,e=/^(www|la|au|fr|de|ch|it|jp|in|kr|nl|es|se|uk)(-(local|dev1|dev2|test1|test2|integ1|integ2|integ3|perf|stage))?\.mathworks\.com$|^ww2(-(local|dev1|dev2|test1|test2|integ1|integ2|integ3|perf|stage))?\.mathworks\.cn$|^www(-(local|dev1|dev2|test1|test2|integ1|integ2|integ3|perf|stage))?\.matlabexpo\.com$/.test(window.location.hostname)?"":"https://www.mathworks.com";fetch(e+"/bin/mathworks/webvitals.json").then(function(g){return g.json()}).then(function(g){window.webVitalsDataConfig=
g;1>g.throttle&&Math.random()>g.throttle&&(a.sendCount=a.maxSend)}).catch(function(g){console.error("Error fetching web vitals JSON:",g)})},addCLSToQueue:function(a){window.webVitalsData.cls=a.value.toFixed(3);if(0<a.value){a=a.entries.reduce(function(g,r){return g.value>r.value?g:r});var e;0<(null==(e=a.sources)?void 0:e.length)&&(window.webVitalsData.clsSource=m.htmlElementToString(a.sources[0].node),window.webVitalsData.clsSourceTree=m.htmlElementToAncestorString(a.sources[0].node))}},addLCPToQueue:function(a){window.webVitalsData.lcp=
Math.round(a.value);a.entries.length&&(a=a.entries[a.entries.length-1],window.webVitalsData.lcpUrl=a.url,window.webVitalsData.lcpTarget=m.htmlElementToString(a.element),window.webVitalsData.lcpTargetTree=m.htmlElementToAncestorString(a.element))},addFCPToQueue:function(a){window.webVitalsData.fcp=Math.round(a.value)},addTTFBToQueue:function(a){window.webVitalsData.ttfb=Math.round(a.value);0<a.entries.length&&(window.webVitalsData.domComplete=Math.round(a.entries[0].domComplete),window.webVitalsData.domInteractive=
Math.round(a.entries[0].domInteractive),window.webVitalsData.entryType=a.entries[0].entryType)},addINPToQueue:function(a){window.webVitalsData.inp=a.value;a.entries.length&&(a=a.entries.reduce(function(e,g){return e.target&&g.target||!e.target&&!g.target?e.duration>g.duration?e:g:e.target?e:g},{duration:0}),window.webVitalsData.inpName=a.name,window.webVitalsData.inpDuration=a.duration,a.target&&(window.webVitalsData.inpTarget=m.htmlElementToString(a.target),window.webVitalsData.inpTargetTree=m.htmlElementToAncestorString(a.target)))},
htmlElementToString:function(a){if(a){var e=a.localName;a.id&&0<a.id.length&&(e+="#"+a.id);a.className&&0<a.className.length&&(e+="."+a.className.trim().replaceAll(/\s+/g,"."));return e}return""},htmlElementToAncestorString:function(a){for(var e="",g;a&&"body"!==(null==(g=a)?void 0:g.localName);)e&&(e=" \x3e "+e),e=m.htmlElementToString(a)+e,a=a.parentElement;return e},generateSessionKey:function(){"undefined"===typeof sessionStorage.cwvSessionId&&(sessionStorage.cwvSessionId="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var e=16*Math.random()|0;return("x"===a?e:e&3|8).toString(16)}));return sessionStorage.cwvSessionId},flushData:function(){window.webVitalsData={}},sendPerformanceData:function(){Object.keys(window.webVitalsData).length&&!location.hostname.includes("aem")&&(m.sendData(window.webVitalsData,"web vitals"),m.flushData())},handleJSError:function(a,e){var g={};g.errorMessage=e.message;e.error&&(g.errorName=e.error.name);try{g.errorFilename=e.filename,g.lineNumber=e.lineno,g.columnNumber=e.colno,
e.error&&(g.errorStack=e.error.stack,g.errorMessage=e.error.message)}catch(r){}a.sendData(g,"javascript")},sendData:function(a,e){if(this.sendCount<this.maxSend){var g="WEB_CORE_WEB_VITALS";"javascript"===e&&(g="JS_ERRORS");a.country=window.MathWorksCountryCode;a.region=window.MathWorksRegionCode;a.userAgent=navigator.userAgent;a.query=location.search;a.host=location.host;a.pathname=location.pathname;"undefined"!==typeof _satellite&&(a.sessionid=_satellite.getVisitorId().getMarketingCloudVisitorID());
e="https://udc-service.mathworks.com/udc/service/v1/events";location.hostname.includes("-")&&(e="https://udc-service-integ3.mathworks.com/udc/service/v1/events");var r;(null==(r=window.webVitalsDataConfig)?0:r.endpoint)&&fetch(e,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json","x-mw-udc-client-version":"1.0","x-mw-udc-application-name":"WEB_PAGE_METRICS","x-mw-udc-application-version":"0.5","x-mw-authentication":window.webVitalsDataConfig.key},cache:"no-cache",keepalive:!0,
body:JSON.stringify({Event:[{sessionKey:this.generateSessionKey(),eventKey:g,eventDate:(new Date).toISOString().slice(0,23),eventData:JSON.stringify(a)}]})});this.sendCount++}}};x.exports=m;m.init()},{"web-vitals":2}],2:[function(v,x,B){!function(n,m){"object"==typeof B&&"undefined"!=typeof x?m(B):"function"==typeof define&&define.amd?define(["exports"],m):m((n="undefined"!=typeof globalThis?globalThis:n||self).webVitals={})}(this,function(n){var m,a,e,g,r,E=-1,y=function(d){addEventListener("pageshow",
function(b){b.persisted&&(E=b.timeStamp,d(b))},!0)},N=function(){var d=self.performance&&performance.getEntriesByType&&performance.getEntriesByType("navigation")[0];if(d&&0<d.responseStart&&d.responseStart<performance.now())return d},I=function(){var d=N();return d&&d.activationStart||0},t=function(d,b){var c=N(),h="navigate";0<=E?h="back-forward-cache":c&&(document.prerendering||0<I()?h="prerender":document.wasDiscarded?h="restore":c.type&&(h=c.type.replace(/_/g,"-")));return{name:d,value:void 0===
b?-1:b,rating:"good",delta:0,entries:[],id:"v4-".concat(Date.now(),"-").concat(Math.floor(8999999999999*Math.random())+1E12),navigationType:h}},C=function(d,b,c){try{if(PerformanceObserver.supportedEntryTypes.includes(d)){var h=new PerformanceObserver(function(f){Promise.resolve().then(function(){b(f.getEntries())})});return h.observe(Object.assign({type:d,buffered:!0},c||{})),h}}catch(f){}},u=function(d,b,c,h){var f,l;return function(k){0<=b.value&&(k||h)&&((l=b.value-(f||0))||void 0===f)&&(f=b.value,
b.delta=l,k=b.value,b.rating=k>c[1]?"poor":k>c[0]?"needs-improvement":"good",d(b))}},O=function(d){requestAnimationFrame(function(){return requestAnimationFrame(function(){return d()})})},F=function(d){document.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&d()})},J=function(d){var b=!1;return function(){b||(d(),b=!0)}},D=-1,K=function(d){"hidden"===document.visibilityState&&-1<D&&(D="visibilitychange"===d.type?d.timeStamp:0,removeEventListener("visibilitychange",
K,!0),removeEventListener("prerenderingchange",K,!0))},Z=function(){addEventListener("visibilitychange",K,!0);addEventListener("prerenderingchange",K,!0)},P=function(){return 0>D&&(D="hidden"!==document.visibilityState||document.prerendering?1/0:0,Z(),y(function(){setTimeout(function(){D="hidden"!==document.visibilityState||document.prerendering?1/0:0;Z()},0)})),{get firstHiddenTime(){return D}}},G=function(d){document.prerendering?addEventListener("prerenderingchange",function(){return d()},!0):
d()},Q=[1800,3E3],aa=function(d,b){b=b||{};G(function(){var c,h=P(),f=t("FCP"),l=C("paint",function(k){k.forEach(function(p){"first-contentful-paint"===p.name&&(l.disconnect(),p.startTime<h.firstHiddenTime&&(f.value=Math.max(p.startTime-I(),0),f.entries.push(p),c(!0)))})});l&&(c=u(d,f,Q,b.reportAllChanges),y(function(k){f=t("FCP");c=u(d,f,Q,b.reportAllChanges);O(function(){f.value=performance.now()-k.timeStamp;c(!0)})}))})},R=[.1,.25],S=0,T=1/0,L=0,ha=function(d){d.forEach(function(b){b.interactionId&&
(T=Math.min(T,b.interactionId),L=Math.max(L,b.interactionId),S=L?(L-T)/7+1:0)})},z=[],M=new Map,ba=0,ia=[],ja=function(d){if(ia.forEach(function(h){return h(d)}),d.interactionId||"first-input"===d.entryType){var b=z[z.length-1],c=M.get(d.interactionId);if(c||10>z.length||d.duration>b.latency)c?d.duration>c.latency?(c.entries=[d],c.latency=d.duration):d.duration===c.latency&&d.startTime===c.entries[0].startTime&&c.entries.push(d):(b={id:d.interactionId,latency:d.duration,entries:[d]},M.set(b.id,b),
z.push(b)),z.sort(function(h,f){return f.latency-h.latency}),10<z.length&&z.splice(10).forEach(function(h){return M.delete(h.id)})}},ca=function(d){var b=self.requestIdleCallback||self.setTimeout,c=-1;return d=J(d),"hidden"===document.visibilityState?d():(c=b(d),F(d)),c},U=[200,500],V=[2500,4E3],W={},X=[800,1800],ka=function c(b){document.prerendering?G(function(){return c(b)}):"complete"!==document.readyState?addEventListener("load",function(){return c(b)},!0):setTimeout(b,0)},H={passive:!0,capture:!0},
la=new Date,fa=function(b,c){a||(a=c,e=b,g=new Date,da(removeEventListener),ea())},ea=function(){if(0<=e&&e<g-la){var b={entryType:"first-input",name:a.type,target:a.target,cancelable:a.cancelable,startTime:a.timeStamp,processingStart:a.timeStamp+e};r.forEach(function(c){c(b)});r=[]}},ma=function(b){if(b.cancelable){var c=(1E12<b.timeStamp?new Date:performance.now())-b.timeStamp;"pointerdown"==b.type?function(h,f){var l=function(){fa(h,f);p()},k=function(){p()},p=function(){removeEventListener("pointerup",
l,H);removeEventListener("pointercancel",k,H)};addEventListener("pointerup",l,H);addEventListener("pointercancel",k,H)}(c,b):fa(c,b)}},da=function(b){["mousedown","keydown","touchstart","pointerdown"].forEach(function(c){return b(c,ma,H)})},Y=[100,300];n.CLSThresholds=R;n.FCPThresholds=Q;n.FIDThresholds=Y;n.INPThresholds=U;n.LCPThresholds=V;n.TTFBThresholds=X;n.onCLS=function(b,c){c=c||{};aa(J(function(){var h,f=t("CLS",0),l=0,k=[],p=function(q){q.forEach(function(w){if(!w.hadRecentInput){var na=
k[0],oa=k[k.length-1];l&&1E3>w.startTime-oa.startTime&&5E3>w.startTime-na.startTime?(l+=w.value,k.push(w)):(l=w.value,k=[w])}});l>f.value&&(f.value=l,f.entries=k,h())},A=C("layout-shift",p);A&&(h=u(b,f,R,c.reportAllChanges),F(function(){p(A.takeRecords());h(!0)}),y(function(){l=0;f=t("CLS",0);h=u(b,f,R,c.reportAllChanges);O(function(){return h()})}),setTimeout(h,0))}))};n.onFCP=aa;n.onFID=function(b,c){c=c||{};G(function(){var h=P(),f=t("FID"),l=function(q){q.startTime<h.firstHiddenTime&&(f.value=
q.processingStart-q.startTime,f.entries.push(q),A(!0))},k=function(q){q.forEach(l)},p=C("first-input",k);var A=u(b,f,Y,c.reportAllChanges);p&&(F(J(function(){k(p.takeRecords());p.disconnect()})),y(function(){f=t("FID");A=u(b,f,Y,c.reportAllChanges);r=[];e=-1;a=null;da(addEventListener);r.push(l);ea()}))})};n.onINP=function(b,c){"PerformanceEventTiming"in self&&"interactionId"in PerformanceEventTiming.prototype&&(c=c||{},G(function(){var h;"interactionCount"in performance||m||(m=C("event",ha,{type:"event",
buffered:!0,durationThreshold:0}));var f=t("INP"),l=function(A){ca(function(){A.forEach(ja);var q;(q=z[Math.min(z.length-1,Math.floor(((m?S:performance.interactionCount||0)-ba)/50))])&&q.latency!==f.value&&(f.value=q.latency,f.entries=q.entries,p())})},k=C("event",l,{durationThreshold:null!==(h=c.durationThreshold)&&void 0!==h?h:40});var p=u(b,f,U,c.reportAllChanges);k&&(k.observe({type:"first-input",buffered:!0}),F(function(){l(k.takeRecords());p(!0)}),y(function(){ba=m?S:performance.interactionCount||
0;z.length=0;M.clear();f=t("INP");p=u(b,f,U,c.reportAllChanges)}))}))};n.onLCP=function(b,c){c=c||{};G(function(){var h=P(),f=t("LCP"),l=function(q){c.reportAllChanges||(q=q.slice(-1));q.forEach(function(w){w.startTime<h.firstHiddenTime&&(f.value=Math.max(w.startTime-I(),0),f.entries=[w],p())})},k=C("largest-contentful-paint",l);if(k){var p=u(b,f,V,c.reportAllChanges);var A=J(function(){W[f.id]||(l(k.takeRecords()),k.disconnect(),W[f.id]=!0,p(!0))});["keydown","click"].forEach(function(q){addEventListener(q,
function(){return ca(A)},{once:!0,capture:!0})});F(A);y(function(q){f=t("LCP");p=u(b,f,V,c.reportAllChanges);O(function(){f.value=performance.now()-q.timeStamp;W[f.id]=!0;p(!0)})})}})};n.onTTFB=function(b,c){c=c||{};var h=t("TTFB"),f=u(b,h,X,c.reportAllChanges);ka(function(){var l=N();l&&(h.value=Math.max(l.responseStart-I(),0),h.entries=[l],f(!0),y(function(){h=t("TTFB",0);(f=u(b,h,X,c.reportAllChanges))(!0)}))})}})},{}]},{},[1]);