(function(){function l(g,h,c){function a(b,f){if(!h[b]){if(!g[b]){var k="function"==typeof require&&require;if(!f&&k)return k(b,!0);if(d)return d(b,!0);f=Error("Cannot find module '"+b+"'");throw f.code="MODULE_NOT_FOUND",f;}f=h[b]={exports:{}};g[b][0].call(f.exports,function(m){return a(g[b][1][m]||m)},f,f.exports,l,g,h,c)}return h[b].exports}for(var d="function"==typeof require&&require,e=0;e<c.length;e++)a(c[e]);return a}return l})()({1:[function(l,g,h){var c={init:function(){document.querySelector("#global_search_container")&&
(c.moveSearchBox(),window.addEventListener("resize",function(){c.moveSearchBox()}));c.stickTop();c.manageOpenMobileMenus();c.manageFocusDropdowns();c.focusSearchBox();var a=document.querySelectorAll("#global_navigation .dropdown-menu");0<a.length&&a.forEach(function(b){b.addEventListener("click",function(f){f.stopPropagation()})});c.escapeStage=1;c.dropdownToggle=document.querySelector("#globalnav_item_search .dropdown-toggle");c.dropdownMenu=document.querySelector("#globalnav_item_search .dropdown-menu");
c.dropdownToggle&&(c.bsDropdownInstance=new bootstrap.Dropdown(c.dropdownToggle,{autoClose:!1}),c.dropdownToggle.addEventListener("hide.bs.dropdown",function(b){c.preventDropdownClose(b)}),c.dropdownMenu&&c.dropdownMenu.addEventListener("hide.bs.dropdown",function(b){c.preventDropdownClose(b)}),c.dropdownToggle.addEventListener("shown.bs.dropdown",function(){c.escapeStage=1}));var d;null==(d=document.getElementById("corporate_nav_modal"))||d.addEventListener("click",function(){var b;null==(b=document.querySelector("header .navbar-toggler:not(.collapsed)"))||
b.click()});var e;null==(e=document.getElementById("sectionHeadSearchDropdown"))||e.addEventListener("click",function(){document.getElementById("site_search_selector").click()});document.addEventListener("keydown",function(b){var f,k=null==(f=b.target)?void 0:f.closest(".input-group");if("Escape"===b.key||"Esc"===b.key)if("query"===b.target.id||k&&k.contains(b.target))b.preventDefault(),b.stopPropagation(),b.stopImmediatePropagation(),c.handleEscapeKey()},!0);document.body.addEventListener("click",
function(b){c.escapeStage=1;"corporate_nav_modal"===b.target.id&&b.target.classList.contains("show")&&c.hideDropdown()})},moveSearchBox:function(){var a=document.querySelector("#global_search_container");if(a){var d=document.querySelector("#global_search_mobile_placeholder"),e=document.querySelector("#global_search_desktop_placeholder"),b=a.previousElementSibling.id;if(991<window.innerWidth&&"global_search_mobile_placeholder"===b&&e){if(e.insertAdjacentElement("afterend",a),document.body.classList.contains("-is_bootstrap3")){var f;
null==(f=document.getElementById("site_search_selector"))||f.addEventListener("click",function(){this.nextElementSibling.style.display="block"===this.nextElementSibling.style.display?"none":"block"})}}else 991>=window.innerWidth&&"global_search_desktop_placeholder"===b&&d&&d.insertAdjacentElement("afterend",a)}},stickTop:function(){var a=document.querySelector("#sticky_container");a&&window.addEventListener("scroll",function(){var d=window.scrollY||window.pageYOffset;0>=a.getBoundingClientRect().top&&
0<d?a.classList.add("-is_locked"):a.classList.remove("-is_locked")})},manageOpenMobileMenus:function(){if(!document.body.classList.contains("-is_bootstrap3")){var a=document.getElementById("global_search_mobile"),d=document.getElementById("global_navigation");a&&d&&(a.addEventListener("show.bs.collapse",function(){(new bootstrap.Collapse(d,{toggle:!1})).hide()}),d.addEventListener("show.bs.collapse",function(){(new bootstrap.Collapse(a,{toggle:!1})).hide()}))}},manageFocusDropdowns:function(){document.querySelectorAll("header .navbar-nav .nav-item.dropdown").forEach(function(a){a.addEventListener("focusout",
function(d){d.relatedTarget&&!a.contains(d.relatedTarget)&&(a.classList.contains("open")||a.querySelector("a.nav-link").classList.contains("show"))&&a.querySelector("a.nav-link").click()})});document.querySelectorAll("header .navbar-toggler").forEach(function(a){var d=document.querySelector(a.dataset.target);[a,d].forEach(function(e){e.addEventListener("focusout",function(b){!b.relatedTarget||a.contains(b.relatedTarget)||d.contains(b.relatedTarget)||!d.classList.contains("show")&&!d.classList.contains("in")||
a.click()})})})},focusSearchBox:function(){var a=document.querySelector("#globalnav_item_search"),d=document.querySelector("#global_search_mobile"),e=document.querySelector("#query");!document.body.classList.contains("-is_bootstrap3")&&a&&d&&e?(a.addEventListener("shown.bs.dropdown",function(){e.focus({preventScroll:!0})}),d.addEventListener("shown.bs.collapse",function(){e.focus({preventScroll:!0})})):a&&d&&e&&($(a).on("shown.bs.dropdown",function(){e.focus({preventScroll:!0})}),$(d).on("shown.bs.collapse",
function(){e.focus({preventScroll:!0})}))},preventDropdownClose:function(a){if(3===this.escapeStage&&this.allowDropdownClose)this.escapeStage=1,this.allowDropdownClose=!1;else{var d=document.querySelector("#query");if(d&&d.value||1!==this.escapeStage)return a.preventDefault(),a.stopImmediatePropagation(),!1}},hideDropdown:function(){this.allowDropdownClose=!0;this.dropdownMenu&&this.dropdownMenu.classList.contains("show")&&(this.dropdownMenu.classList.remove("show"),this.dropdownToggle&&(this.dropdownToggle.classList.remove("show"),
this.dropdownToggle.setAttribute("aria-expanded","false")),this.bsDropdownInstance&&this.bsDropdownInstance.hide());this.escapeStage=1},handleEscapeKey:function(){var a=document.querySelector("#query");(null==a?0:a.value)?(this.escapeStage=2,a.value="",a&&"function"===typeof a.focus&&a.focus()):(this.escapeStage=3,this.allowDropdownClose=!0,this.bsDropdownInstance&&c.dropdownMenu&&c.dropdownMenu.classList.contains("show")&&this.bsDropdownInstance.hide(),this.escapeStage=1,this.allowDropdownClose=
!1)}};g.exports=c;document.addEventListener("DOMContentLoaded",function(){c.init()})},{}]},{},[1]);